# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'Enter name as it appears in the book metadata', max_length=254)),
                ('trp_id', models.CharField(help_text=b'Optional: This value will be auto-generated by the server if the field is left blank or non-unique value is entered', unique=True, max_length=15, blank=True)),
                ('alternate_names', models.CharField(help_text=b'Optional: enter alternate names separated by a semi-colon', max_length=254, null=True, blank=True)),
                ('external_id', models.CharField(help_text=b'Optional: enter Ulan id in the form of a URL; if there is no Ulan id, enter LCCN in the form of a URL', max_length=254, null=True, blank=True)),
                ('birth_date', models.CharField(help_text=b'Optional: enter birth date as yyyy-mm-dd (for sorting and filtering)', max_length=25, null=True, blank=True)),
                ('death_date', models.CharField(help_text=b'Optional: enter death date as yyyy-mm-dd', max_length=25, null=True, blank=True)),
                ('roles', models.CharField(help_text=b'Optional: enter roles, separated by a semi-colon', max_length=254, null=True, blank=True)),
                ('bio', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'biographies',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('slug', models.SlugField(max_length=254)),
                ('author', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('text', models.TextField()),
                ('pids', models.CharField(help_text=b'Comma-separated list of pids for books or prints associated with this essay.', max_length=254, null=True, blank=True)),
                ('people', models.ManyToManyField(help_text=b'List of people associated with this essay.', to='rome_app.Biography', null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.CharField(unique=True, max_length=50)),
                ('external_id', models.CharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.CharField(unique=True, max_length=50)),
                ('external_id', models.CharField(max_length=50, blank=True)),
            ],
        ),
    ]
