# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0002_auto_20170829_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='people',
            field=models.ManyToManyField(blank=True, help_text=b'List of people associated with this essay.', to='rome_app.Biography'),
        ),
    ]
