# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0003_auto_20171206_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='slug',
            field=models.SlugField(max_length=191),
        ),
    ]
