# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0006_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='', max_length=191),
            preserve_default=False,
        ),
    ]
