# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0008_auto_20190830_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
