# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0008_auto_20190710_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='roles',
            new_name='family',
        ),
    ]
