# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-07 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0009_auto_20190710_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='end_date',
            field=models.CharField(blank=True, help_text='Optional: enter death date as yyyy-mm-dd', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='start_date',
            field=models.CharField(blank=True, help_text='Optional: enter birth date as yyyy-mm-dd (for sorting and filtering)', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='shopdocument',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rome_app.Shop'),
        ),
    ]
