# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0010_auto_20190807_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('text', models.TextField()),
                ('document_file', models.FileField(upload_to='')),
                ('people', models.ManyToManyField(blank=True, help_text='List of people associated with this essay.', to='rome_app.Biography')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopdocument',
            name='shop',
        ),
        migrations.DeleteModel(
            name='ShopDocument',
        ),
        migrations.AddField(
            model_name='shop',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='List of documents associated with this shop.', to='rome_app.Document'),
        ),
    ]
