# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0011_auto_20190811_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default='doc', max_length=191),
            preserve_default=False,
        ),
    ]
