# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0012_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
