# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0013_auto_20190812_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
