# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0014_document_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='consagra',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
