# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rome_app', '0015_document_consagra'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
